# Generated by Django 4.2.10 on 2024-04-24 23:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_managers_users_date_joined_users_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Servicio_Solicitado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.clientes', to_field='email')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.services')),
            ],
            options={
                'verbose_name': 'Servicio Solicitado',
                'verbose_name_plural': 'Servicios Solicitados',
            },
        ),
        migrations.DeleteModel(
            name='quote_requests',
        ),
    ]
